# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class LogAnomaly(BaseModel):
    service_name: typing.Optional[str] = Field(default=None, description='The service, component, daemon, or process that generated the anomaly (e.g., sshd, dfs.DataNode, mod_jk, nova.compute)')
    timestamp: typing.Optional[str] = Field(default=None, description='Timestamp from the log line. Normalize to ISO 8601 (YYYY-MM-DDTHH:MM:SS) where possible, otherwise preserve as-is')
    error_severity: typing.Optional[types.ErrorSeverity] = None
    raw_log_line: typing.Optional[str] = Field(default=None, description='The exact verbatim log line(s) that represent the anomaly, including any stack trace lines directly associated')
    suggested_remediation: typing.Optional[str] = Field(default=None, description='Specific, actionable remediation steps an SRE should take to resolve this issue')

class TriageResult(BaseModel):
    anomalies: typing.List["LogAnomaly"]
    has_critical_issues: typing.Optional[bool] = Field(default=None, description='True if any anomaly has CRITICAL severity')
    summary: typing.Optional[str] = Field(default=None, description='One sentence summary of the most significant issue found, or \'No anomalies detected\' if anomalies is empty')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
