# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class CausalStep(BaseModel):
    step: typing.Optional[int] = None
    event: typing.Optional[str] = Field(default=None, description='what happened at this step, in plain English')

class IncidentCard(BaseModel):
    service_name: typing.Optional[str] = Field(default=None, description='service/component that emitted this, inferred from the event; do not invent')
    timestamp: typing.Optional[str] = Field(default=None, description='ISO timestamp of the event, copied verbatim from the input')
    error_severity: typing.Optional[types.Severity] = None
    anomaly_type: typing.Optional[types.AnomalyType] = None
    root_cause: typing.Optional[str] = Field(default=None, description='one-sentence plain-English explanation of what actually broke')
    causal_chain: typing.List["CausalStep"] = Field(description='ordered steps reconstructed from the session timeline; empty array if no timeline was given')
    suggested_remediation: typing.Optional[str] = Field(default=None, description='a concrete, actionable fix - not generic advice')
    confidence: typing.Optional[float] = Field(default=None, description='0.0 to 1.0 confidence in this diagnosis')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
