# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class ErrorSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

# #########################################################################
# Generated classes (2)
# #########################################################################

class LogAnomaly(BaseModel):
    service_name: str = Field(description='The service, component, daemon, or process that generated the anomaly (e.g., sshd, dfs.DataNode, mod_jk, nova.compute)')
    timestamp: str = Field(description='Timestamp from the log line. Normalize to ISO 8601 (YYYY-MM-DDTHH:MM:SS) where possible, otherwise preserve as-is')
    error_severity: ErrorSeverity
    raw_log_line: str = Field(description='The exact verbatim log line(s) that represent the anomaly, including any stack trace lines directly associated')
    suggested_remediation: str = Field(description='Specific, actionable remediation steps an SRE should take to resolve this issue')

class TriageResult(BaseModel):
    anomalies: typing.List["LogAnomaly"]
    has_critical_issues: bool = Field(description='True if any anomaly has CRITICAL severity')
    summary: str = Field(description='One sentence summary of the most significant issue found, or \'No anomalies detected\' if anomalies is empty')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
