# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class AnomalyType(str, Enum):
    SeverityError = "SeverityError"
    FailureKeyword = "FailureKeyword"
    RareEvent = "RareEvent"
    SequenceDeviation = "SequenceDeviation"

class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

# #########################################################################
# Generated classes (2)
# #########################################################################

class CausalStep(BaseModel):
    step: int
    event: str = Field(description='what happened at this step, in plain English')

class IncidentCard(BaseModel):
    service_name: typing.Optional[str] = Field(default=None, description='service/component that emitted this, inferred from the event; null only if truly indeterminable')
    timestamp: typing.Optional[str] = Field(default=None, description='ISO timestamp of the event, copied verbatim from the input')
    error_severity: Severity
    anomaly_type: AnomalyType
    root_cause: str = Field(description='one-sentence plain-English explanation of what actually broke')
    causal_chain: typing.List["CausalStep"] = Field(description='ordered steps reconstructed from the session timeline; empty array if no timeline was given')
    suggested_remediation: str = Field(description='a concrete, actionable fix - not generic advice')
    confidence: float = Field(description='0.0 to 1.0 confidence in this diagnosis')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
