# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CausalStep": types.CausalStep,
    "stream_types.CausalStep": stream_types.CausalStep,

    "types.IncidentCard": types.IncidentCard,
    "stream_types.IncidentCard": stream_types.IncidentCard,


    "types.AnomalyType": types.AnomalyType,

    "types.Severity": types.Severity,

}